### ISSUE TITLE
Webmention.rock-Test failed

### ISSUE THREAD

**Issue by Libralop** [sebsel/seblog-kirby-webmentions#3]
I've installed the plugin today (upload and renaming the directory), put the code

`<link rel="webmention" href="<?php echo url('webmention') ?>">`

in the header snippet and

`<?php echo webmentions() ?>`

in the article template. The path to webmention.php is 

`/site/plugins/webmentions/webmentions.php`

Problem: The "Receiver Test #1" (https://webmention.rocks/) failed with the following messages:

-------

Sending Webmention
source=https://webmention.rocks/receive/1/e41d313390255d40e36b46a471de2839
target=http://libralop.de/tagebuch/2017-05-02

Discovering Webmention endpoint
http://libralop.de/webmention

Sending Webmention
Response Code: 400
{
    "status": "error",
    "code": 400,
    "message": "Undefined property: Obj::$lang",
    "data": []
}

Your Webmention endpoint did not return a valid HTTP status code. The raw response from your Webmention endpoint is displayed above.

-------

I'm using:

- Toolkit Version: 2.4.1
- Kirby Version: 2.4.1
- Panel Version: 2.4.1

What can I do?

**Comment by sebsel** [comment]
Hmm, that's sad.

I've encountered this error too when a webmention was sent to my homepage instead of a post. I've updated the plugin to also work with the homepage now.

But, it seems like the other pages on your site give the same error, so it has to be something else. I think it means the router can't find your page. (At least that's what it was with the homepage.) Sadly, I don't really know how to debug that from here for you.

Maybe I should start a new Webmentions Plugin, start fresh and with a clean Kirby installation, to make sure it still works for other sites. Mine is highly customised at the moment.

**Comment by sebsel** [comment]
Found out why this was!

I use some weird router hack (checkout https://github.com/sebsel/seblog-kirby-webmentions/commit/0751d5decc357774ca8a327b23f22d5c4d456c98 for the code) to fetch pages through Kirby's router. That's actually a bit harder than you would think. (Seems like they are going to fix things in [Kirby 3](https://github.com/k-next/http/tree/master/src/HTTP/Router).)

Anyway, the original plugin only found pages with a 'native' route / a URL that's just the name of the folder in `content`. I fixed that for myself, but it turned out that my old code only fetched pages with a [custom route](https://getkirby.com/docs/developer-guide/advanced/routing). The new code fetches both.

Sorry for the wait! I am working on a fresh and new version of this plugin, that's why I found out :)
